from __future__ import annotations

import os
from dataclasses import dataclass


def env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if not raw:
        return default
    return float(raw)


def env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if not raw:
        return default
    return int(raw)


@dataclass(frozen=True)
class Settings:
    database_url: str = "postgresql+psycopg://postgres:postgres@localhost:5432/cn_ops"
    persistence_provider: str = "auto"
    app_env: str = "local"
    x_provider: str = "fixture"
    allow_live_x_api: bool = False
    allow_live_x_write: bool = False
    allow_live_search: bool = False
    allow_live_llm: bool = False
    allow_non_test_mode_write: bool = False
    require_operator_approval: bool = True
    monthly_x_api_budget_usd: float = 1950.0
    daily_x_api_budget_usd: float = 25.0
    per_candidate_search_budget: int = 8
    search_provider: str = "fixture"
    llm_provider: str = "fixture"
    llm_model: str = ""
    x_bearer_token: str = ""
    brave_search_api_key: str = ""
    openai_api_key: str = ""
    secret_key: str = "dev-only-change-me"
    min_neutrality_score: float = 0.75
    min_helpfulness_probability: float = 0.60
    min_claim_opinion_score: float = 0.30
    admission_claim_opinion_high_min: float = 0.30
    admission_claim_opinion_low_max: float = 0.30
    admission_url_validity_high_min: float = 0.95
    admission_harassment_abuse_high_min: float = 0.98
    community_notes_data_use_purpose: str = "community_notes_ai_note_writing"
    operational_evals_directly_necessary: bool = True
    track_a_requires_express_consent: bool = True
    require_bot_identity_disclosure: bool = True
    bot_profile_disclosure: str = "Fixture AI Note Writer bot: proposed notes are generated by an automated system for Community Notes AI note writing."
    bot_responsible_party: str = "Ellen Sun"
    usage_api_reconciliation_required: bool = True
    developer_console_reconciliation_required: bool = True
    emergency_stop_external_writes: bool = False
    emergency_stop_reason: str = ""
    approved_multimodal_workflow_enabled: bool = False
    governance_policy_version: str = "community-notes14-governance-v1"

    @classmethod
    def from_env(cls) -> "Settings":
        return cls(
            database_url=os.getenv("DATABASE_URL", cls.database_url),
            persistence_provider=os.getenv("PERSISTENCE_PROVIDER", cls.persistence_provider),
            app_env=os.getenv("APP_ENV", cls.app_env),
            x_provider=os.getenv("X_PROVIDER", cls.x_provider),
            allow_live_x_api=env_bool("ALLOW_LIVE_X_API", cls.allow_live_x_api),
            allow_live_x_write=env_bool("ALLOW_LIVE_X_WRITE", cls.allow_live_x_write),
            allow_live_search=env_bool("ALLOW_LIVE_SEARCH", cls.allow_live_search),
            allow_live_llm=env_bool("ALLOW_LIVE_LLM", cls.allow_live_llm),
            allow_non_test_mode_write=env_bool("ALLOW_NON_TEST_MODE_WRITE", cls.allow_non_test_mode_write),
            require_operator_approval=env_bool("REQUIRE_OPERATOR_APPROVAL", cls.require_operator_approval),
            monthly_x_api_budget_usd=env_float("MONTHLY_X_API_BUDGET_USD", cls.monthly_x_api_budget_usd),
            daily_x_api_budget_usd=env_float("DAILY_X_API_BUDGET_USD", cls.daily_x_api_budget_usd),
            per_candidate_search_budget=env_int("PER_CANDIDATE_SEARCH_BUDGET", cls.per_candidate_search_budget),
            search_provider=os.getenv("SEARCH_PROVIDER", cls.search_provider),
            llm_provider=os.getenv("LLM_PROVIDER", cls.llm_provider),
            llm_model=os.getenv("LLM_MODEL", cls.llm_model),
            x_bearer_token=os.getenv("X_BEARER_TOKEN", cls.x_bearer_token),
            brave_search_api_key=os.getenv("BRAVE_SEARCH_API_KEY", cls.brave_search_api_key),
            openai_api_key=os.getenv("OPENAI_API_KEY", cls.openai_api_key),
            secret_key=os.getenv("SECRET_KEY", cls.secret_key),
            min_neutrality_score=env_float("MIN_NEUTRALITY_SCORE", cls.min_neutrality_score),
            min_helpfulness_probability=env_float("MIN_HELPFULNESS_PROBABILITY", cls.min_helpfulness_probability),
            min_claim_opinion_score=env_float("MIN_CLAIM_OPINION_SCORE", cls.min_claim_opinion_score),
            community_notes_data_use_purpose=os.getenv("COMMUNITY_NOTES_DATA_USE_PURPOSE", cls.community_notes_data_use_purpose),
            operational_evals_directly_necessary=env_bool(
                "OPERATIONAL_EVALS_DIRECTLY_NECESSARY",
                cls.operational_evals_directly_necessary,
            ),
            track_a_requires_express_consent=env_bool("TRACK_A_REQUIRES_EXPRESS_CONSENT", cls.track_a_requires_express_consent),
            require_bot_identity_disclosure=env_bool("REQUIRE_BOT_IDENTITY_DISCLOSURE", cls.require_bot_identity_disclosure),
            bot_profile_disclosure=os.getenv("BOT_PROFILE_DISCLOSURE", cls.bot_profile_disclosure),
            bot_responsible_party=os.getenv("BOT_RESPONSIBLE_PARTY", cls.bot_responsible_party),
            usage_api_reconciliation_required=env_bool("USAGE_API_RECONCILIATION_REQUIRED", cls.usage_api_reconciliation_required),
            developer_console_reconciliation_required=env_bool(
                "DEVELOPER_CONSOLE_RECONCILIATION_REQUIRED",
                cls.developer_console_reconciliation_required,
            ),
            emergency_stop_external_writes=env_bool("EMERGENCY_STOP_EXTERNAL_WRITES", cls.emergency_stop_external_writes),
            emergency_stop_reason=os.getenv("EMERGENCY_STOP_REASON", cls.emergency_stop_reason),
            approved_multimodal_workflow_enabled=env_bool(
                "APPROVED_MULTIMODAL_WORKFLOW_ENABLED",
                cls.approved_multimodal_workflow_enabled,
            ),
            governance_policy_version=os.getenv("GOVERNANCE_POLICY_VERSION", cls.governance_policy_version),
        )

    def postgres_persistence_enabled(self) -> bool:
        if self.persistence_provider == "postgres":
            return True
        if self.persistence_provider == "memory":
            return False
        return self.app_env != "local" and bool(self.database_url)

    def data_use_scope_allowed(self) -> bool:
        return self.community_notes_data_use_purpose == "community_notes_ai_note_writing"

    def operational_evals_scope_allowed(self) -> bool:
        return self.operational_evals_directly_necessary and self.data_use_scope_allowed()

    def bot_identity_configured(self) -> bool:
        if not self.require_bot_identity_disclosure:
            return True
        return bool(self.bot_profile_disclosure.strip()) and bool(self.bot_responsible_party.strip())

    def policy_scope(self) -> dict:
        return {
            "community_notes_data_use_purpose": self.community_notes_data_use_purpose,
            "data_use_scope_allowed": self.data_use_scope_allowed(),
            "operational_evals_directly_necessary": self.operational_evals_directly_necessary,
            "operational_evals_scope_allowed": self.operational_evals_scope_allowed(),
            "policy_text": (
                "Process X Community Notes API data solely for Community Notes AI note writing. "
                "Run evaluation only when directly necessary to operate that note-writing workflow."
            ),
        }

    def bot_identity(self) -> dict:
        return {
            "required": self.require_bot_identity_disclosure,
            "configured": self.bot_identity_configured(),
            "profile_disclosure": self.bot_profile_disclosure,
            "responsible_party": self.bot_responsible_party,
        }

    def public_dict(self) -> dict:
        return {
            "app_env": self.app_env,
            "persistence_provider": "postgres" if self.postgres_persistence_enabled() else "memory",
            "x_provider": self.x_provider,
            "allow_live_x_api": self.allow_live_x_api,
            "allow_live_x_write": self.allow_live_x_write,
            "allow_live_search": self.allow_live_search,
            "allow_live_llm": self.allow_live_llm,
            "allow_non_test_mode_write": self.allow_non_test_mode_write,
            "require_operator_approval": self.require_operator_approval,
            "monthly_x_api_budget_usd": self.monthly_x_api_budget_usd,
            "daily_x_api_budget_usd": self.daily_x_api_budget_usd,
            "per_candidate_search_budget": self.per_candidate_search_budget,
            "search_provider": self.search_provider,
            "llm_provider": self.llm_provider,
            "llm_model_configured": bool(self.llm_model),
            "x_credentials_configured": bool(self.x_bearer_token),
            "search_credentials_configured": bool(self.brave_search_api_key),
            "llm_credentials_configured": bool(self.openai_api_key),
            "min_neutrality_score": self.min_neutrality_score,
            "min_helpfulness_probability": self.min_helpfulness_probability,
            "min_claim_opinion_score": self.min_claim_opinion_score,
            "policy_scope": self.policy_scope(),
            "track_a_requires_express_consent": self.track_a_requires_express_consent,
            "bot_identity": self.bot_identity(),
            "usage_api_reconciliation_required": self.usage_api_reconciliation_required,
            "developer_console_reconciliation_required": self.developer_console_reconciliation_required,
            "emergency_stop_external_writes": self.emergency_stop_external_writes,
            "emergency_stop_reason": self.emergency_stop_reason,
            "approved_multimodal_workflow_enabled": self.approved_multimodal_workflow_enabled,
            "governance_policy_version": self.governance_policy_version,
        }
